name: pos_caja
description: "VaraNova-PosCaja"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: any

  sqflite: any
  path: any
  path_provider: any
  shared_preferences: any

  share_plus: any
  xml: any
  file_picker: any
  cross_file: any

  crypto: any
  encrypt: any
  device_info_plus: any

  intl: any
  uuid: any
  
  another_telephony: any
  vibration: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  flutter_launcher_icons: any

flutter:
  uses-material-design: true

  assets:
    - assets/icon/appicon.png

flutter_launcher_icons:
  android: true
  image_path: "assets/icon/appicon.png"
  adaptive_icon_background: "#FFFFFF"
