name: Build & Obfuscate

on:
  push:
    branches: main
              develop 
              POSC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      # ── BUILD ────────────────────────────────────────
      - name: Build Obfuscated APK
        run: |
          flutter build apk --release

      # ── ARTIFACTS ────────────────────────────────────
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: VaraNova-APK
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload Symbols
        uses: actions/upload-artifact@v4
        with:
          name: VaraNova-Symbols
          path: build/app/outputs/symbols